### ISSUE TITLE
[Fabric 1.19] 0.8.6 & 0.8.5 freeze while launching.

### ISSUE THREAD

**Issue by greensad** [SigmundGranaas/forgero#161]
Freezes on the Dashloader screen but the screen displayed is red and uses unknown characters where the text is normally printed. (Loader is PolyMC)

[Crash Log](https://mclo.gs/xzTuery)

![image](https://user-images.githubusercontent.com/10079877/175132791-a96e2364-9a15-4df4-b0c4-be4d7d2a3019.png)

**Comment by Wilevar** [comment]
I'm having a similar issue. Once the game finishes loading (lot of mods, so I can't rule out a mod conflict yet. I'll test that shortly.) it seems to repeatedly reload the resource pack with the following error in output log:

16:47:08.817
net.minecraft.class_310
Render thread
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 2
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.1)
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 2
	at com.sigmundgranaas.forgero.client.texture.FabricTextureIdentifierFactory.createToolPartTextureIdentifier(FabricTextureIdentifierFactory.java:32)
	at net.minecraft.resource.LifecycledResourceManagerImpl.handler$chf000$getResource(LifecycledResourceManagerImpl:2036)
	at net.minecraft.resource.LifecycledResourceManagerImpl.getResource(LifecycledResourceManagerImpl)
	at net.minecraft.client.texture.SpriteAtlasTexture.handler$bhb000$onTailLoadSprites(SpriteAtlasTexture:1563)
	at net.minecraft.client.texture.SpriteAtlasTexture.loadSprites(SpriteAtlasTexture:214)
	at net.minecraft.client.texture.SpriteAtlasTexture.stitch(SpriteAtlasTexture:124)
	at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader:226)
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:52)
	at net.minecraft.client.render.model.BakedModelManager.prepare(BakedModelManager:19)
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18791(SinglePreparationResourceReloader:11)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
	
Hopefully that helps some.

**Comment by SigmundGranaas** [comment]
I might have rushed that update a little bit to fast. It's pretty clear which method is causing the issue, it's a really bad implementation. I'll have to check if this is a compatability issue or if there's something wrong with the base setup.

**Comment by SigmundGranaas** [comment]
[forgero-0.8.6-BETA-1.19.0.zip](https://github.com/SigmundGranaas/forgero/files/8961360/forgero-0.8.6-BETA-1.19.0.zip)

Could you test if this version fixes the issue?

I'll update the mod to 0.8.7 if it fixes the issue.

**Comment by Wilevar** [comment]
Some notes on mod conflict testing:
- The mod also works with [BRRP](https://www.curseforge.com/minecraft/mc-mods/better-runtime-resource-pack).
- I've found that the mod works fine with a number of core/library mods and interface mods. Issues began showing up when I added a number of mods that affect world generation, so I'm trying to narrow down which ones actually conflict. (AwesomeDungeons/Nether/End/Ocean, Better End/Nether, Immersive Weathering, More Geodes, Repurposed Structures, The Graveyard.) I'll reply shortly with what ones-

Oh, new message. Sure, I'll try with the zip you uploaded. I assume that's different from the current 0.8.6-BETA I'm currently using from the main site.

**Comment by SigmundGranaas** [comment]
Yep, it's only slightly updated

**Comment by Wilevar** [comment]
K. Downloaded and testing with the mods that caused a conflict. ^_^

**Comment by SigmundGranaas** [comment]
Also, thanks for doing the integration testing with other mods. I appreciate it!

**Comment by Wilevar** [comment]
Happy to help.
Good news! So far it seems to be working. 

I'll add in the rest of my mods (All 97 of them, which will bring the total in this pack to 166) and let you know if it has any conflict loading like before. ^_^

Just FYI, this is also using BRRP instead of ARRP, since a big block mod requires it and BRRP contains the code of ARRP + fixes, allegedly.

**Comment by SigmundGranaas** [comment]
> Some notes on mod conflict testing:
> 
>     * The mod also works with [BRRP](https://www.curseforge.com/minecraft/mc-mods/better-runtime-resource-pack).

I am planning on creating my own fork of ARRP which would fit my need for generating resources, but I might base it on BRRP instead if it brings significant enhancements. I'll see when I get around to it.

**Comment by SigmundGranaas** [comment]
Great! Version 0.9.0 also brings significant enhancements to the texture processing and identification pipeline, which makes it a lot more resilient to errors like this. I'll probably have it ready in a couple of days.

**Comment by Wilevar** [comment]
> > Some notes on mod conflict testing:
> > ```
> > * The mod also works with [BRRP](https://www.curseforge.com/minecraft/mc-mods/better-runtime-resource-pack).
> > ```
> 
> I am planning on creating my own fork of ARRP which would fit my need for generating resources, but I might base it on BRRP instead if it brings significant enhancements. I'll see when I get around to it.

Understood. I just know that having both ARRP and BRRP loading together caused an immediate "Can't load these together" error and loading stop, so some testing will be needed with your fork to make sure it doesn't cause people to be unable to load BRRP alongside it.

.... Aaand loaded! Alongside 165 other mods, it's no longer creating the loading loop error. ^_^

**Comment by SigmundGranaas** [comment]
Great! I released the 0.8.7 mods on Curseforge.

Yeah, I'll have a look at BRRP first to see if it suits my needs better. Going the hard route always causes more issues and debugging time...

**Comment by SigmundGranaas** [comment]
I'll close the issue if the new version fixes the issue for @greensad  as well.

**Comment by Wilevar** [comment]
And it loads in the server, connection's good, no issues.

I don't see the guidebook though in REI. Patchuli is updated and I have that, so I'll assume that's just a matter of it not being in the current development build yet unless you tell me otherwise. lol

**Comment by SigmundGranaas** [comment]
Guidebook can be crafted by combining most things forgero related with a book. But it will also be awarded through achievements when you pick up your first parts. The book might be a little dated, and will probably also need some updates for 1.19.

**Comment by Wilevar** [comment]
K. No worries. ^_^
Just no recipe in REI, but that's not a big deal. It's honestly more immersive if the Guidebook is something you maybe find as loot, maybe specifically in village smith chests or some such. Your call of course. Just wanted to mention the lack of recipe in case it was meant to be there.

**Comment by greensad** [comment]
Looking all clear on my end, I'll just go ahead and close it!
