### ISSUE TITLE
Still crashing soulEntity with Identity mod

### ISSUE THREAD

**Issue by Borailuce99** [SigmundGranaas/forgero#812]
Hi, I recently updated forgero mod to version 0.11.9 and saw that 0.11.8 added a solution to my last issue posted here #801. But I tested it again and the game still crashes with the following crash-report:

java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.follow_range
	at net.minecraft.class_5132.method_26865(class_5132.java:22)
	at net.minecraft.class_5132.method_26862(class_5132.java:28)
	at net.minecraft.class_5131.method_26852(class_5131.java:76)
	at net.minecraft.class_1309.method_26825(class_1309.java:1904)
	at net.minecraft.class_1408.<init>(class_1408.java:84)
	at net.minecraft.class_1407.<init>(class_1407.java:16)
	at com.sigmundgranaas.forgero.minecraft.common.entity.SoulEntity$1.<init>(SoulEntity.java:75)
	at com.sigmundgranaas.forgero.minecraft.common.entity.SoulEntity.method_5965(SoulEntity.java:75)
	at net.minecraft.class_1308.<init>(class_1308.java:141)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1296.<init>(class_1296.java:29)
	at net.minecraft.class_1429.<init>(class_1429.java:43)
	at com.sigmundgranaas.forgero.minecraft.common.entity.SoulEntity.<init>(SoulEntity.java:66)
	at com.sigmundgranaas.forgero.minecraft.common.entity.Entities.lambda$register$0(Entities.java:21)
	at net.minecraft.class_1299.method_5883(class_1299.java:544)
	at draylar.identity.api.variant.IdentityType.getAllTypes(IdentityType.java:91)
	at draylar.identity.screen.IdentityScreen.populateRenderEntities(IdentityScreen.java:218)
	at draylar.identity.screen.IdentityScreen.<init>(IdentityScreen.java:54)
	at draylar.identity.impl.tick.MenuKeyPressHandler.tick(MenuKeyPressHandler.java:17)
	at draylar.identity.impl.tick.MenuKeyPressHandler.tick(MenuKeyPressHandler.java:9)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at jdk.proxy2/jdk.proxy2.$Proxy192.tick(Unknown Source)
	at dev.architectury.event.fabric.EventHandlerImpl.lambda$registerClient$2(EventHandlerImpl.java:54)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$0(ClientTickEvents.java:34)
	at net.minecraft.class_310.handler$cid000$fabric-lifecycle-events-v1$onStartTick(class_310.java:11517)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Does this mean that the same error is still taking place or is it a new error from the last changes?

Thanks a lot for your support. Merry Christmas!

**Comment by SigmundGranaas** [comment]
It was supposed to fix the issue, but I don't understand what is causing this issue. I didn't bother trying to fix it anymore, so I'll just disable the Soul entity. It'll be Fixed by #815
